"""Add meaning doctrine phase 1

Revision ID: 368602c8dcc7
Revises: b50e0840f1bf
Create Date: 2026-06-30 11:17:23.661024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368602c8dcc7'
down_revision: Union[str, Sequence[str], None] = 'b50e0840f1bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('proof_type', sa.String(), nullable=True))
    op.add_column('media', sa.Column('linked_entity_type', sa.String(), nullable=True))
    op.add_column('media', sa.Column('linked_entity_id', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('visibility_state', sa.String(), nullable=False, server_default='anonymous'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'visibility_state')
    op.drop_column('media', 'linked_entity_id')
    op.drop_column('media', 'linked_entity_type')
    op.drop_column('media', 'proof_type')
    op.drop_column('media', 'size')
    # ### end Alembic commands ###
