"""Add deterministic TrustScore Phase 2

Revision ID: 8389f01bed73
Revises: 368602c8dcc7
Create Date: 2026-06-30 11:29:04.982439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8389f01bed73'
down_revision: Union[str, Sequence[str], None] = '368602c8dcc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trust_scores')
    op.create_table('trust_scores',
        sa.Column('profile_id', sa.String(), nullable=False),
        sa.Column('proof_count', sa.Integer(), nullable=True, default=0),
        sa.Column('work_proof_count', sa.Integer(), nullable=True, default=0),
        sa.Column('opportunity_completion_rate', sa.Float(), nullable=True, default=0.0),
        sa.Column('visibility_score', sa.Integer(), nullable=True, default=0),
        sa.Column('last_updated', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('profile_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trust_scores')
    op.create_table('trust_scores',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('profile_id', sa.String(), nullable=False),
        sa.Column('reliability_score', sa.Float(), nullable=True),
        sa.Column('response_speed_score', sa.Float(), nullable=True),
        sa.Column('completion_score', sa.Float(), nullable=True),
        sa.Column('consistency_score', sa.Float(), nullable=True),
        sa.Column('overall_trust', sa.Float(), nullable=True),
        sa.Column('archetype_trust', sqlite.JSON(), nullable=True),
        sa.Column('geo_trust', sqlite.JSON(), nullable=True),
        sa.Column('last_updated', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('profile_id')
    )
    # ### end Alembic commands ###
