"""consolidate_startup_mutations

Revision ID: a763f5689f23
Revises: c7614bb67711
Create Date: 2026-08-15 12:04:43.283577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a763f5689f23'
down_revision: Union[str, Sequence[str], None] = 'c7614bb67711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_identity_mapping',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('global_it_tenant_id', sa.String(), nullable=False),
    sa.Column('iphande_profile_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['iphande_profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_identity_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_identity_mapping_global_it_tenant_id'), ['global_it_tenant_id'], unique=True)

    op.create_table('followups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advertisements', schema=None) as batch_op:
        pass

    with op.batch_alter_table('continuity_captures', schema=None) as batch_op:
        pass

    with op.batch_alter_table('continuity_events', schema=None) as batch_op:
        pass

    with op.batch_alter_table('earning_ledgers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_earning_ledgers_payment_intent_id'))
        batch_op.create_index(batch_op.f('ix_earning_ledgers_payment_intent_id'), ['payment_intent_id'], unique=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        pass

    with op.batch_alter_table('fee_ledgers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_fee_ledgers_idempotency_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_fee_ledgers_idempotency_key'))
        batch_op.create_index(batch_op.f('ix_fee_ledgers_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.drop_index(batch_op.f('ix_fee_ledgers_payment_intent_id'))
        batch_op.create_index(batch_op.f('ix_fee_ledgers_payment_intent_id'), ['payment_intent_id'], unique=True)

    with op.batch_alter_table('financial_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(), nullable=True))

    with op.batch_alter_table('giving', schema=None) as batch_op:
        pass

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        pass

    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        pass

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        pass

    with op.batch_alter_table('ledger_immutability_logs', schema=None) as batch_op:
        pass

    with op.batch_alter_table('merchant_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchant_accounts_user_id'))
        batch_op.create_index(batch_op.f('ix_merchant_accounts_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('payment_intents', schema=None) as batch_op:
        batch_op.alter_column('quote_id', existing_type=sa.UUID(), nullable=True)
        batch_op.alter_column('invoice_id', existing_type=sa.UUID(), nullable=True)
        batch_op.add_column(sa.Column('opportunity_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('idempotency_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('provider_event_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ledger_processed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_payment_intents_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_intents_provider_event_id'), ['provider_event_id'], unique=False)
        batch_op.create_foreign_key('fk_payment_intents_opportunity_id', 'opportunities', ['opportunity_id'], ['id'])

    with op.batch_alter_table('platform_configs', schema=None) as batch_op:
        pass

    with op.batch_alter_table('proofs_of_payment', schema=None) as batch_op:
        pass

    with op.batch_alter_table('quote_requests', schema=None) as batch_op:
        pass

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        pass

    with op.batch_alter_table('treasury_ledgers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treasury_ledgers_fee_ledger_id'))
        batch_op.create_index(batch_op.f('ix_treasury_ledgers_fee_ledger_id'), ['fee_ledger_id'], unique=True)
        batch_op.drop_index(batch_op.f('ix_treasury_ledgers_payment_intent_id'))
        batch_op.create_index(batch_op.f('ix_treasury_ledgers_payment_intent_id'), ['payment_intent_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_treasury_ledgers_idempotency_key'), ['idempotency_key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treasury_ledgers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treasury_ledgers_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_treasury_ledgers_payment_intent_id'))
        batch_op.create_index(batch_op.f('ix_treasury_ledgers_payment_intent_id'), ['payment_intent_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_treasury_ledgers_fee_ledger_id'))
        batch_op.create_index(batch_op.f('ix_treasury_ledgers_fee_ledger_id'), ['fee_ledger_id'], unique=False)
        batch_op.alter_column('reversal_continuity_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('continuity_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('fee_ledger_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('payment_intent_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.alter_column('accepted_continuity_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('sent_continuity_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('continuity_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('quote_requests', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('proofs_of_payment', schema=None) as batch_op:
        batch_op.alter_column('continuity_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('payment_intent_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('platform_configs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('payment_intents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_intents_opportunity_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payment_intents_provider_event_id'))
        batch_op.drop_index(batch_op.f('ix_payment_intents_idempotency_key'))
        batch_op.alter_column('receipt_continuity_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('financial_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('confirmed_continuity_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('continuity_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('quote_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               nullable=False)
        batch_op.alter_column('invoice_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('ledger_processed_at')
        batch_op.drop_column('provider_event_id')
        batch_op.drop_column('idempotency_key')
        batch_op.drop_column('opportunity_id')

    with op.batch_alter_table('merchant_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchant_accounts_user_id'))
        batch_op.create_index(batch_op.f('ix_merchant_accounts_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('ledger_immutability_logs', schema=None) as batch_op:
        batch_op.alter_column('ledger_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('paid_continuity_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('continuity_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('quote_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.alter_column('balance_continuity_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('continuity_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('inventory_item_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('giving', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('financial_events', schema=None) as batch_op:
        batch_op.alter_column('continuity_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('idempotency_key')

    with op.batch_alter_table('fee_ledgers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_ledgers_payment_intent_id'))
        batch_op.create_index(batch_op.f('ix_fee_ledgers_payment_intent_id'), ['payment_intent_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_fee_ledgers_idempotency_key'))
        batch_op.create_index(batch_op.f('ix_fee_ledgers_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_fee_ledgers_idempotency_key'), ['idempotency_key'])
        batch_op.alter_column('fee_allocation_continuity_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('treasury_transaction_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('earning_ledger_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('payment_intent_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('earning_ledgers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_earning_ledgers_payment_intent_id'))
        batch_op.create_index(batch_op.f('ix_earning_ledgers_payment_intent_id'), ['payment_intent_id'], unique=False)
        batch_op.alter_column('status_change_continuity_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('created_continuity_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('payout_request_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('payout_batch_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('payment_intent_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('merchant_account_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('continuity_events', schema=None) as batch_op:
        batch_op.alter_column('parent_event_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('continuity_captures', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('advertisements', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.drop_table('followups')
    with op.batch_alter_table('tenant_identity_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_identity_mapping_global_it_tenant_id'))

    op.drop_table('tenant_identity_mapping')
    # ### end Alembic commands ###
