import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import requests
from io import BytesIO

def draw_header(c, profile, doc_type, doc_id, date_str):
    c.saveState()
    
    # Header logo
    logo_drawn = False
    if profile.company_logo_url:
        try:
            response = requests.get(profile.company_logo_url, timeout=5)
            if response.status_code == 200:
                img_data = BytesIO(response.content)
                img = ImageReader(img_data)
                # Keep aspect ratio
                c.drawImage(img, 2*cm, A4[1] - 4*cm, width=4*cm, preserveAspectRatio=True, mask='auto')
                logo_drawn = True
        except Exception as e:
            print(f"Failed to load logo: {e}")
    
    if not logo_drawn:
        c.setFont("Helvetica-Bold", 24)
        c.setFillColor(colors.HexColor("#111827"))
        c.drawString(2*cm, A4[1] - 3*cm, profile.name or "iPhande Steward")
    
    # Doc Type & Details
    c.setFont("Helvetica-Bold", 20)
    c.setFillColor(colors.HexColor("#111827"))
    c.drawRightString(A4[0] - 2*cm, A4[1] - 2.5*cm, doc_type.upper())
    
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#4B5563"))
    c.drawRightString(A4[0] - 2*cm, A4[1] - 3*cm, f"Reference: {doc_id}")
    c.drawRightString(A4[0] - 2*cm, A4[1] - 3.5*cm, f"Date: {date_str}")
    
    # Profile Info
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor("#111827"))
    y_offset = A4[1] - 5*cm
    c.drawString(2*cm, y_offset, profile.name)
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#4B5563"))
    if profile.phone:
        y_offset -= 0.5*cm
        c.drawString(2*cm, y_offset, profile.phone)
    if profile.email:
        y_offset -= 0.5*cm
        c.drawString(2*cm, y_offset, profile.email)
    if profile.city or profile.province:
        y_offset -= 0.5*cm
        loc = ", ".join(filter(None, [profile.suburb, profile.city, profile.province]))
        c.drawString(2*cm, y_offset, loc)

    c.restoreState()
    return y_offset - 1*cm

def draw_footer(c, doc_id, date_str, steward_id, ref_number):
    c.saveState()
    
    # Document Lineage Block
    y = 4.5*cm
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(colors.HexColor("#6B7280"))
    c.drawString(2*cm, y, "DOCUMENT LINEAGE")
    
    y -= 0.4*cm
    c.setFont("Helvetica", 8)
    c.drawString(2*cm, y, f"Document ID: {doc_id}")
    y -= 0.4*cm
    c.drawString(2*cm, y, f"Generated Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    y -= 0.4*cm
    c.drawString(2*cm, y, f"Steward ID: {steward_id}")
    y -= 0.4*cm
    c.drawString(2*cm, y, f"Reference: {ref_number}")
    
    # Bottom Footer
    c.setFont("Helvetica-Oblique", 9)
    c.setFillColor(colors.HexColor("#9CA3AF"))
    c.drawCentredString(A4[0]/2.0, 1.5*cm, "Generated by iPhande — work remembered, trust preserved.")
    c.restoreState()

def generate_quote_pdf(quote, profile):
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    
    # Header
    doc_id = f"IPH-Q-{str(quote.id).split('-')[0].upper()}"
    date_str = quote.created_at.strftime("%B %d, %Y")
    y = draw_header(c, profile, "Quote", doc_id, date_str)
    
    # Customer Details
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor("#111827"))
    c.drawString(2*cm, y, "Bill To:")
    y -= 0.6*cm
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#4B5563"))
    c.drawString(2*cm, y, quote.customer_name)
    if quote.customer_phone:
        y -= 0.5*cm
        c.drawString(2*cm, y, quote.customer_phone)
    
    y -= 1*cm
    
    # Description
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor("#111827"))
    c.drawString(2*cm, y, "Service Description:")
    y -= 0.6*cm
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#4B5563"))
    # Multiline text approximation
    textobject = c.beginText(2*cm, y)
    for line in quote.description.split("\n"):
        textobject.textLine(line)
    c.drawText(textobject)
    y -= (len(quote.description.split("\n")) * 0.5*cm) + 1*cm
    
    # Line Items Table Header
    c.setFillColor(colors.HexColor("#F3F4F6"))
    c.rect(2*cm, y, A4[0] - 4*cm, 0.8*cm, fill=1, stroke=0)
    c.setFillColor(colors.HexColor("#111827"))
    c.setFont("Helvetica-Bold", 10)
    c.drawString(2.5*cm, y + 0.25*cm, "Description")
    c.drawRightString(A4[0] - 6*cm, y + 0.25*cm, "Qty")
    c.drawRightString(A4[0] - 4*cm, y + 0.25*cm, "Unit Price")
    c.drawRightString(A4[0] - 2.5*cm, y + 0.25*cm, "Total")
    
    y -= 0.5*cm
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#4B5563"))
    
    # Line Items Body
    if quote.line_items:
        for item in quote.line_items:
            y -= 0.7*cm
            c.drawString(2.5*cm, y, item.get('description', 'Item'))
            c.drawRightString(A4[0] - 6*cm, y, str(item.get('quantity', 1)))
            c.drawRightString(A4[0] - 4*cm, y, f"R {float(item.get('unit_price', 0)):.2f}")
            c.drawRightString(A4[0] - 2.5*cm, y, f"R {float(item.get('total', 0)):.2f}")
    else:
        y -= 0.7*cm
        c.drawString(2.5*cm, y, "Main Service")
        c.drawRightString(A4[0] - 6*cm, y, "1")
        c.drawRightString(A4[0] - 4*cm, y, f"R {float(quote.amount or 0):.2f}")
        c.drawRightString(A4[0] - 2.5*cm, y, f"R {float(quote.amount or 0):.2f}")
        
    y -= 0.5*cm
    c.setStrokeColor(colors.HexColor("#E5E7EB"))
    c.line(2*cm, y, A4[0] - 2*cm, y)
    
    # Totals
    y -= 1*cm
    if quote.subtotal and float(quote.subtotal) != float(quote.amount):
        c.drawString(A4[0] - 7*cm, y, "Subtotal:")
        c.drawRightString(A4[0] - 2.5*cm, y, f"R {float(quote.subtotal):.2f}")
        y -= 0.6*cm
        
    if quote.vat and float(quote.vat) > 0:
        c.drawString(A4[0] - 7*cm, y, "VAT:")
        c.drawRightString(A4[0] - 2.5*cm, y, f"R {float(quote.vat):.2f}")
        y -= 0.6*cm
        
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor("#111827"))
    c.drawString(A4[0] - 7*cm, y, "Total:")
    c.drawRightString(A4[0] - 2.5*cm, y, f"R {float(quote.amount):.2f}")
    
    y -= 1.5*cm
    if quote.terms:
        c.setFont("Helvetica-Bold", 10)
        c.drawString(2*cm, y, "Terms & Conditions:")
        y -= 0.5*cm
        c.setFont("Helvetica", 9)
        c.setFillColor(colors.HexColor("#4B5563"))
        textobject = c.beginText(2*cm, y)
        for line in quote.terms.split("\n"):
            textobject.textLine(line)
        c.drawText(textobject)
    
    draw_footer(c, doc_id, date_str, profile.id, quote.id)
    
    c.save()
    buffer.seek(0)
    return buffer

def generate_invoice_pdf(invoice, quote, profile):
    # Almost identical to Quote, but titled INVOICE. Let's do a simple wrap for now.
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    
    doc_id = f"IPH-INV-{str(invoice.id).split('-')[0].upper()}"
    date_str = invoice.created_at.strftime("%B %d, %Y")
    y = draw_header(c, profile, "Invoice", doc_id, date_str)
    
    # Customer Details
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor("#111827"))
    c.drawString(2*cm, y, "Bill To:")
    y -= 0.6*cm
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#4B5563"))
    c.drawString(2*cm, y, quote.customer_name if quote else "Unknown")
    
    y -= 1*cm
    
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor("#111827"))
    c.drawString(2*cm, y, "Service Description:")
    y -= 0.6*cm
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#4B5563"))
    
    # Safe multiline handle
    textobject = c.beginText(2*cm, y)
    description = getattr(quote, 'description', '') if quote else 'General Service'
    for line in description.split("\n"):
        textobject.textLine(line)
    c.drawText(textobject)
    y -= (len(description.split("\n")) * 0.5*cm) + 1*cm
    
    c.setFillColor(colors.HexColor("#F3F4F6"))
    c.rect(2*cm, y, A4[0] - 4*cm, 0.8*cm, fill=1, stroke=0)
    c.setFillColor(colors.HexColor("#111827"))
    c.setFont("Helvetica-Bold", 10)
    c.drawString(2.5*cm, y + 0.25*cm, "Description")
    c.drawRightString(A4[0] - 2.5*cm, y + 0.25*cm, "Amount")
    
    y -= 0.5*cm
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#4B5563"))
    
    line_items = getattr(quote, 'line_items', None) if quote else None
    if line_items:
        for item in line_items:
            y -= 0.7*cm
            c.drawString(2.5*cm, y, item.get('description', 'Item'))
            c.drawRightString(A4[0] - 2.5*cm, y, f"R {float(item.get('total', item.get('unit_price', 0))):.2f}")
    else:
        y -= 0.7*cm
        c.drawString(2.5*cm, y, "Main Service")
        c.drawRightString(A4[0] - 2.5*cm, y, f"R {float(invoice.amount or 0):.2f}")
        
    y -= 0.5*cm
    c.setStrokeColor(colors.HexColor("#E5E7EB"))
    c.line(2*cm, y, A4[0] - 2*cm, y)
    
    # Totals
    y -= 1*cm
    
    subtotal = getattr(quote, 'subtotal', None) if quote else None
    if subtotal and float(subtotal) != float(invoice.amount):
        c.drawString(A4[0] - 7*cm, y, "Subtotal:")
        c.drawRightString(A4[0] - 2.5*cm, y, f"R {float(subtotal):.2f}")
        y -= 0.6*cm
        
    vat = getattr(quote, 'vat', None) if quote else None
    if vat and float(vat) > 0:
        c.drawString(A4[0] - 7*cm, y, "VAT:")
        c.drawRightString(A4[0] - 2.5*cm, y, f"R {float(vat):.2f}")
        y -= 0.6*cm
        
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor("#111827"))
    c.drawString(A4[0] - 7*cm, y, "Total:")
    c.drawRightString(A4[0] - 2.5*cm, y, f"R {float(invoice.amount):.2f}")
    
    y -= 1*cm
    amount_paid = getattr(invoice, 'amount_paid', getattr(invoice, 'paid_amount', 0))
    if str(invoice.status) == "InvoiceStatus.paid" or invoice.status == "paid":
         amount_paid = invoice.amount
         
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#10B981"))
    c.drawString(A4[0] - 7*cm, y, "Paid:")
    c.drawRightString(A4[0] - 2.5*cm, y, f"R {float(amount_paid):.2f}")
    
    y -= 1.5*cm
    terms = getattr(quote, 'terms', '') if quote else ''
    if terms:
        c.setFont("Helvetica-Bold", 10)
        c.setFillColor(colors.HexColor("#111827"))
        c.drawString(2*cm, y, "Terms & Notes:")
        y -= 0.5*cm
        c.setFont("Helvetica", 9)
        c.setFillColor(colors.HexColor("#4B5563"))
        textobject = c.beginText(2*cm, y)
        for line in terms.split("\n"):
            textobject.textLine(line)
        c.drawText(textobject)
    
    draw_footer(c, doc_id, date_str, profile.id, getattr(invoice, 'quote_id', invoice.id))
    
    c.save()
    buffer.seek(0)
    return buffer
