from sqlalchemy import Column, String, DateTime, ForeignKey, Text, BigInteger, Identity, CheckConstraint, select
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy import JSON
from sqlalchemy.sql import func
from sqlalchemy import event
import uuid
from src.database import Base

class ContinuityEvent(Base):
    __tablename__ = 'continuity_events'
    __table_args__ = (
        CheckConstraint('parent_event_id != id', name='check_no_self_parent'),
    )

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, nullable=False)
    # The deterministic operational sequence generated by the database
    lineage_sequence = Column(BigInteger, Identity(start=1, cycle=False), unique=True, index=True, nullable=False)
    business_owner_id = Column(String, nullable=False)
    business_category_key = Column(String, nullable=True)
    business_line = Column(String, nullable=True)
    event_type = Column(String, nullable=False)  # e.g., 'business_identity_created', 'content_generated', etc.
    evidence_type = Column(String, nullable=True)
    title = Column(String, nullable=True)
    description = Column(String, nullable=True)
    source = Column(String, nullable=True)
    actor_type = Column(String, nullable=True)   # e.g., 'user', 'customer', 'system'
    actor_id = Column(String, nullable=True)
    related_entity_type = Column(String, nullable=True)  # e.g., 'profile', 'post', 'quote_request', etc.
    related_entity_id = Column(String, nullable=True)
    parent_event_id = Column(UUID(as_uuid=True), ForeignKey('continuity_events.id'), nullable=True)
    payload_json = Column(JSON, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)


@event.listens_for(ContinuityEvent, "before_update")
def prevent_event_update(mapper, connection, target):
    raise RuntimeError("Immutable Timeline Doctrine Violation: ContinuityEvent records cannot be updated. They are append-only.")

@event.listens_for(ContinuityEvent, "before_delete")
def prevent_event_delete(mapper, connection, target):
    raise RuntimeError("Immutable Timeline Doctrine Violation: ContinuityEvent records cannot be deleted. They are append-only.")


@event.listens_for(ContinuityEvent, "before_insert")
def assign_sqlite_lineage_sequence(mapper, connection, target):
    if connection.dialect.name != "sqlite" or target.lineage_sequence is not None:
        return

    next_sequence = connection.execute(
        select(func.coalesce(func.max(ContinuityEvent.lineage_sequence), 0) + 1)
    ).scalar_one()
    target.lineage_sequence = next_sequence
