import uuid
from decimal import Decimal
from typing import List, Dict, Any
from sqlalchemy.orm import Session
from src.database import SessionLocal
from src.models.lead_offer import AffiliateOffer, PayoutModel

DISCHEM_FUNERAL_TIERS = [
    {"cr_min": 0.0, "cr_max": 0.0299, "payout": 0.0},
    {"cr_min": 0.03, "cr_max": 0.0399, "payout": 18.0},
    {"cr_min": 0.04, "cr_max": 0.0499, "payout": 24.0},
    {"cr_min": 0.05, "cr_max": 0.0599, "payout": 30.0},
    {"cr_min": 0.06, "cr_max": 0.0699, "payout": 36.0},
    {"cr_min": 0.07, "cr_max": 0.0799, "payout": 42.0},
    {"cr_min": 0.08, "cr_max": 0.0899, "payout": 48.0},
    {"cr_min": 0.09, "cr_max": 0.0999, "payout": 54.0},
    {"cr_min": 0.10, "cr_max": 0.1099, "payout": 60.0},
    {"cr_min": 0.11, "cr_max": 0.1199, "payout": 66.0},
    {"cr_min": 0.12, "cr_max": 0.1299, "payout": 72.0},
    {"cr_min": 0.13, "cr_max": 0.1399, "payout": 78.0},
    {"cr_min": 0.14, "cr_max": 0.1499, "payout": 84.0},
    {"cr_min": 0.15, "cr_max": 0.1599, "payout": 90.0},
    {"cr_min": 0.16, "cr_max": 0.1699, "payout": 96.0},
    {"cr_min": 0.17, "cr_max": 0.1799, "payout": 102.0},
    {"cr_min": 0.18, "cr_max": 0.1899, "payout": 108.0},
    {"cr_min": 0.19, "cr_max": 0.1999, "payout": 114.0},
    {"cr_min": 0.20, "cr_max": 1.0, "payout": 120.0},
]

DISCHEM_LIFE_TIERS = [
    {"cr_min": 0.0, "cr_max": 0.0499, "payout": 0.0},
    {"cr_min": 0.05, "cr_max": 0.0599, "payout": 40.0},
    {"cr_min": 0.06, "cr_max": 0.0699, "payout": 48.0},
    {"cr_min": 0.07, "cr_max": 0.0799, "payout": 56.0},
    {"cr_min": 0.08, "cr_max": 0.0899, "payout": 64.0},
    {"cr_min": 0.09, "cr_max": 0.0999, "payout": 72.0},
    {"cr_min": 0.10, "cr_max": 0.1099, "payout": 80.0},
    {"cr_min": 0.11, "cr_max": 0.1199, "payout": 88.0},
    {"cr_min": 0.12, "cr_max": 0.1299, "payout": 96.0},
    {"cr_min": 0.13, "cr_max": 0.1399, "payout": 104.0},
    {"cr_min": 0.14, "cr_max": 0.1499, "payout": 112.0},
    {"cr_min": 0.15, "cr_max": 0.1599, "payout": 120.0},
    {"cr_min": 0.16, "cr_max": 0.1699, "payout": 128.0},
    {"cr_min": 0.17, "cr_max": 0.1799, "payout": 136.0},
    {"cr_min": 0.18, "cr_max": 0.1899, "payout": 144.0},
    {"cr_min": 0.19, "cr_max": 0.1999, "payout": 152.0},
    {"cr_min": 0.20, "cr_max": 1.0, "payout": 160.0},
]

ONELIFE_LIFE_TIERS = [
    {"cr_min": 0.0, "cr_max": 0.0099, "payout": 0.0},
    {"cr_min": 0.01, "cr_max": 0.05, "payout": 55.0},
    {"cr_min": 0.051, "cr_max": 0.09, "payout": 58.0},
    {"cr_min": 0.091, "cr_max": 0.13, "payout": 63.0},
    {"cr_min": 0.131, "cr_max": 1.0, "payout": 68.0},
]

AFFILIATE_OFFERS_SEED_DATA: List[Dict[str, Any]] = [
    # --- MEDICAL INSURANCE ---
    {
        "slug": "flexicare-medical-insurance",
        "name": "Flexicare Medical Insurance",
        "category": "MEDICAL",
        "client_name": "Flexicare",
        "channel": "Web",
        "payout_model": PayoutModel.CPA.value,
        "base_payout": Decimal("250.00"),
        "payout_percentage": None,
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("8000.00"),
        "min_age": 18,
        "max_age": 60,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "dedup_period_days": 90,
    },
    # --- LOANS ---
    {
        "slug": "lime-loans",
        "name": "Lime Loans",
        "category": "LOANS",
        "client_name": "Lime",
        "channel": "Web",
        "payout_model": PayoutModel.CPA.value,
        "base_payout": Decimal("200.00"),
        "payout_percentage": None,
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("10000.00"),
        "min_age": 20,
        "max_age": 60,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "dedup_period_days": 90,
    },
    {
        "slug": "mpowa-loans",
        "name": "Mpowa Loans",
        "category": "LOANS",
        "client_name": "Mpowa",
        "channel": "Web",
        "payout_model": PayoutModel.CPA.value,
        "base_payout": Decimal("140.00"),
        "payout_percentage": None,
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("10000.00"),
        "min_age": 20,
        "max_age": 60,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "dedup_period_days": 90,
    },
    {
        "slug": "boodle-loans",
        "name": "Boodle Loans",
        "category": "LOANS",
        "client_name": "Boodle",
        "channel": "Web",
        "payout_model": PayoutModel.CPA.value,
        "base_payout": Decimal("175.00"),
        "payout_percentage": None,
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("10000.00"),
        "min_age": 20,
        "max_age": 60,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "dedup_period_days": 90,
    },
    {
        "slug": "fasta-loans",
        "name": "Fasta Loans",
        "category": "LOANS",
        "client_name": "Fasta",
        "channel": "Web",
        "payout_model": PayoutModel.CPS.value,
        "base_payout": Decimal("0.00"),
        "payout_percentage": Decimal("0.025"),  # 2.5% of loan
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("10000.00"),
        "min_age": 20,
        "max_age": 60,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "dedup_period_days": 90,
    },
    {
        "slug": "wonga-loans",
        "name": "Wonga Loans",
        "category": "LOANS",
        "client_name": "Wonga",
        "channel": "Web",
        "payout_model": PayoutModel.CPA.value,
        "base_payout": Decimal("140.00"),
        "payout_percentage": None,
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("10000.00"),
        "min_age": 20,
        "max_age": 60,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "dedup_period_days": 90,
    },
    {
        "slug": "finchoice-loans",
        "name": "Finchoice Loans",
        "category": "LOANS",
        "client_name": "Finchoice",
        "channel": "Web",
        "payout_model": PayoutModel.CPS.value,
        "base_payout": Decimal("0.00"),
        "payout_percentage": Decimal("0.015"),  # 1.5% of loan
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("10000.00"),
        "min_age": 20,
        "max_age": 60,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "dedup_period_days": 90,
    },
    {
        "slug": "prime-loans",
        "name": "Prime Loans",
        "category": "LOANS",
        "client_name": "Prime Loans",
        "channel": "Web",
        "payout_model": PayoutModel.CPA.value,
        "base_payout": Decimal("115.00"),
        "payout_percentage": None,
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("10000.00"),
        "min_age": 20,
        "max_age": 60,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "dedup_period_days": 90,
    },
    {
        "slug": "lendplus-loans",
        "name": "LendPlus Loans",
        "category": "LOANS",
        "client_name": "LendPlus",
        "channel": "Web",
        "payout_model": PayoutModel.CPA.value,
        "base_payout": Decimal("157.00"),
        "payout_percentage": None,
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("10000.00"),
        "min_age": 20,
        "max_age": 60,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "dedup_period_days": 90,
    },
    {
        "slug": "crediwise-loans",
        "name": "Crediwise Loans",
        "category": "LOANS",
        "client_name": "Crediwise",
        "channel": "Web",
        "payout_model": PayoutModel.CPA.value,
        "base_payout": Decimal("32.00"),
        "payout_percentage": None,
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("10000.00"),
        "min_age": 20,
        "max_age": 60,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "dedup_period_days": 90,
    },
    {
        "slug": "century-finance-loans",
        "name": "Century Finance Loans",
        "category": "LOANS",
        "client_name": "Century Finance",
        "channel": "Web",
        "payout_model": PayoutModel.CPA.value,
        "base_payout": Decimal("200.00"),
        "payout_percentage": None,
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("10000.00"),
        "min_age": 20,
        "max_age": 60,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "dedup_period_days": 90,
    },
    {
        "slug": "sunshine-loans",
        "name": "Sunshine Loans",
        "category": "LOANS",
        "client_name": "Sunshine Loans",
        "channel": "Web",
        "payout_model": PayoutModel.CPA.value,
        "base_payout": Decimal("120.00"),
        "payout_percentage": None,
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("10000.00"),
        "min_age": 20,
        "max_age": 60,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "dedup_period_days": 90,
    },
    # --- FUNERAL COVER ---
    {
        "slug": "1life-funeral",
        "name": "1Life Funeral Cover",
        "category": "FUNERAL",
        "client_name": "1Life",
        "channel": "Web",
        "payout_model": PayoutModel.CPA.value,
        "base_payout": Decimal("300.00"),
        "payout_percentage": None,
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("5000.00"),
        "min_age": 20,
        "max_age": 60,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "dedup_period_days": 90,
    },
    {
        "slug": "dischem-funeral",
        "name": "Dis-Chem Funeral Cover",
        "category": "FUNERAL",
        "client_name": "Dis-Chem",
        "channel": "Web",
        "payout_model": PayoutModel.TIERED_CPL.value,
        "base_payout": Decimal("0.00"),
        "payout_percentage": None,
        "payout_tier_rules": DISCHEM_FUNERAL_TIERS,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("5000.00"),
        "min_age": 20,
        "max_age": 60,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "dedup_period_days": 90,
    },
    # --- LIFE COVER ---
    {
        "slug": "dischem-life",
        "name": "Dis-Chem Life Cover",
        "category": "LIFE",
        "client_name": "Dis-Chem",
        "channel": "Web",
        "payout_model": PayoutModel.TIERED_CPL.value,
        "base_payout": Decimal("0.00"),
        "payout_percentage": None,
        "payout_tier_rules": DISCHEM_LIFE_TIERS,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("5000.00"),
        "min_age": 20,
        "max_age": 60,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "dedup_period_days": 90,
    },
    {
        "slug": "1life-life-cover",
        "name": "1Life Life Cover",
        "category": "LIFE",
        "client_name": "1Life",
        "channel": "Warm-up/Email",
        "payout_model": PayoutModel.TIERED_CPL.value,
        "base_payout": Decimal("0.00"),
        "payout_percentage": None,
        "payout_tier_rules": ONELIFE_LIFE_TIERS,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("5000.00"),
        "min_age": 20,
        "max_age": 60,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "dedup_period_days": 90,
    },
    # --- VEHICLE / TRACKING ---
    {
        "slug": "cartrack-dashcams",
        "name": "Cartrack Dashcams",
        "category": "VEHICLE",
        "client_name": "Cartrack",
        "channel": "Web",
        "payout_model": PayoutModel.CPL.value,
        "base_payout": Decimal("55.00"),
        "payout_percentage": None,
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("5000.00"),
        "min_age": 25,
        "max_age": 65,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": True,
        "dedup_period_days": 90,
    },
    {
        "slug": "car-insurance-white-label",
        "name": "Car Insurance (White Label)",
        "category": "VEHICLE",
        "client_name": "White Label Insurance",
        "channel": "SMS/Warm Up/Web Service",
        "payout_model": PayoutModel.CPL.value,
        "base_payout": Decimal("70.00"),
        "payout_percentage": None,
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("5000.00"),
        "min_age": 25,
        "max_age": 65,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": True,
        "dedup_period_days": 90,
    },
    {
        "slug": "motor-warranty-white-label",
        "name": "Motor Warranty (White Label)",
        "category": "VEHICLE",
        "client_name": "White Label Insurance",
        "channel": "SMS/Warm Up/Web Service",
        "payout_model": PayoutModel.CPL.value,
        "base_payout": Decimal("50.00"),
        "payout_percentage": None,
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("5000.00"),
        "min_age": 25,
        "max_age": 65,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": True,
        "dedup_period_days": 90,
    },
    {
        "slug": "vehicle-tracker-white-label",
        "name": "Vehicle Tracker (White Label)",
        "category": "VEHICLE",
        "client_name": "White Label Insurance",
        "channel": "SMS/Warm Up/Web Service",
        "payout_model": PayoutModel.CPL.value,
        "base_payout": Decimal("50.00"),
        "payout_percentage": None,
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("5000.00"),
        "min_age": 25,
        "max_age": 65,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": True,
        "dedup_period_days": 90,
    },
    {
        "slug": "legal-cover-white-label",
        "name": "Legal Cover (White Label)",
        "category": "LEGAL",
        "client_name": "White Label Legal",
        "channel": "SMS/Warm Up/Web Service",
        "payout_model": PayoutModel.CPL.value,
        "base_payout": Decimal("50.00"),
        "payout_percentage": None,
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("5000.00"),
        "min_age": 18,
        "max_age": 65,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "dedup_period_days": 90,
    },
    {
        "slug": "car-finance-rejected",
        "name": "Car Finance Second Chance",
        "category": "VEHICLE",
        "client_name": "Second Chance Auto",
        "channel": "Web",
        "payout_model": PayoutModel.CPL.value,
        "base_payout": Decimal("1.50"),
        "payout_percentage": None,
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("5000.00"),
        "min_age": 20,
        "max_age": 65,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": True,
        "dedup_period_days": 90,
    },
    # --- RETAIL & INVESTMENTS ---
    {
        "slug": "cotton-on",
        "name": "Cotton On",
        "category": "RETAIL",
        "client_name": "Cotton On",
        "channel": "SMS/Warm Up/Web Service",
        "payout_model": PayoutModel.CPS.value,
        "base_payout": Decimal("0.00"),
        "payout_percentage": Decimal("0.06"),  # 6% CPS
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": None,
        "min_age": 18,
        "max_age": 65,
        "requires_employment": False,
        "requires_bank_account": False,
        "requires_sa_citizen": False,
        "requires_driver_license": False,
        "dedup_period_days": 30,
    },
    {
        "slug": "sanlam-retirement-annuity",
        "name": "Sanlam Retirement Annuity",
        "category": "INVESTMENTS",
        "client_name": "Sanlam",
        "channel": "Web",
        "payout_model": PayoutModel.HYBRID.value,
        "base_payout": Decimal("250.00"),  # R10 CPL + R250 CPA
        "payout_percentage": None,
        "payout_tier_rules": {"cpl": 10.0, "cpa": 250.0},
        "merchant_split_ratio": Decimal("0.70"),
        "min_income": Decimal("10000.00"),
        "min_age": 20,
        "max_age": 55,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "dedup_period_days": 90,
    },
    # --- DIGITAL TOOLS & CLOUD ---
    {
        "slug": "hostafrica-cloud-domains",
        "name": "HOSTAFRICA Domain & Business Email Hosting",
        "category": "DIGITAL_TOOLS",
        "client_name": "HOSTAFRICA (Pty) Ltd",
        "channel": "Web / Dashboard",
        "payout_model": PayoutModel.CPS.value,
        "base_payout": Decimal("0.00"),
        "payout_percentage": Decimal("0.10"),  # 10% CPS recurring
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.70"),
        "affiliate_base_url": "https://my.hostafrica.com/aff.php?aff=3635",
        "description": "Register custom .co.za domains, professional business email, and cloud hosting for your enterprise.",
        "min_income": None,
        "min_age": 18,
        "max_age": 75,
        "requires_employment": False,
        "requires_bank_account": True,
        "requires_sa_citizen": False,
        "requires_driver_license": False,
        "requires_fica": False,
        "dedup_period_days": 30,
    },
    # --- WEALTH & FRACTIONAL INVESTING ---
    {
        "slug": "easyequities-invest",
        "name": "EasyEquities Fractional Shares & TFSA",
        "category": "WEALTH_AND_SAVINGS",
        "client_name": "EasyEquities",
        "channel": "Web / Mobile App",
        "payout_model": PayoutModel.CPA.value,
        "base_payout": Decimal("50.00"),  # R50 starter investment voucher credit
        "payout_percentage": None,
        "payout_tier_rules": None,
        "merchant_split_ratio": Decimal("0.80"),  # 80% to user/merchant
        "affiliate_base_url": "https://bit.ly/3byDlco",
        "description": "Join +2 million investors. Start buying local & US shares with no minimum deposit and receive a R50 starter voucher.",
        "min_income": None,
        "min_age": 18,
        "max_age": 75,
        "requires_employment": False,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": False,
        "requires_fica": True,
        "dedup_period_days": 90,
    },
    # --- AUTOMOTIVE DEALERSHIP & FINANCING FUNNEL ---
    {
        "slug": "mad-cars-dealership",
        "name": "Mad Cars Pre-Owned & New Vehicle Finance",
        "category": "VEHICLE_DEALERSHIP",
        "client_name": "Mad Cars Dealership",
        "channel": "Web / In-Store Lead Capture",
        "payout_model": PayoutModel.HYBRID.value,
        "base_payout": Decimal("200.00"),  # R200 per qualified finance application
        "payout_percentage": None,
        "payout_tier_rules": {
            "cpl": 200.00,                 # R200 per qualified vetted lead
            "cps": 2500.00,                # R2,500 average commission upon car delivery / payout
        },
        "merchant_split_ratio": Decimal("0.70"),  # 70% to referring merchant / agent
        "affiliate_base_url": "https://api.iphande.co.za/api/v1/affiliates/leads/vehicle-inquiry",
        "description": "Browse quality pre-owned hatchbacks, bakkies, and sedans. Get pre-approved vehicle finance with Mad Cars.",
        "min_income": Decimal("10000.00"),        # Minimum R10k salary for vehicle asset finance
        "min_age": 21,
        "max_age": 65,
        "requires_employment": True,
        "requires_bank_account": True,
        "requires_sa_citizen": True,
        "requires_driver_license": True,          # Must have valid Code B / EB driver's license
        "requires_fica": True,
        "dedup_period_days": 90,
    },
]


def seed_affiliate_offers(db: Session) -> int:
    """Seeds or updates affiliate offers from the Aff.co.za master sheet."""
    inserted_or_updated = 0
    for data in AFFILIATE_OFFERS_SEED_DATA:
        existing = db.query(AffiliateOffer).filter(AffiliateOffer.slug == data["slug"]).first()
        if existing:
            for k, v in data.items():
                setattr(existing, k, v)
        else:
            offer = AffiliateOffer(**data)
            db.add(offer)
        inserted_or_updated += 1
    db.commit()
    return inserted_or_updated


if __name__ == "__main__":
    db = SessionLocal()
    try:
        count = seed_affiliate_offers(db)
        print(f"[SUCCESS] Successfully seeded/synced {count} affiliate offers.")
    finally:
        db.close()
