"""initial schema with places

Revision ID: 9e9512b0d039
Revises: 
Create Date: 2026-06-16 10:11:15.390517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9512b0d039'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continuity_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lineage_sequence', sa.BigInteger(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('business_owner_id', sa.String(), nullable=False),
    sa.Column('business_category_key', sa.String(), nullable=True),
    sa.Column('business_line', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('related_entity_type', sa.String(), nullable=True),
    sa.Column('related_entity_id', sa.String(), nullable=True),
    sa.Column('parent_event_id', sa.UUID(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('parent_event_id != id', name='check_no_self_parent'),
    sa.ForeignKeyConstraint(['parent_event_id'], ['continuity_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_continuity_events_lineage_sequence'), 'continuity_events', ['lineage_sequence'], unique=True)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_owner_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('receipt_photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_business_owner_id'), 'expenses', ['business_owner_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_owner_id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_business_owner_id'), 'inventory_items', ['business_owner_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('profile_slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('service_needed', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_owner_id'), 'leads', ['owner_id'], unique=False)
    op.create_table('places',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('place_code', sa.String(), nullable=False),
    sa.Column('parent_place_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('province_code', sa.String(), nullable=True),
    sa.Column('province_name', sa.String(), nullable=True),
    sa.Column('district_code', sa.String(), nullable=True),
    sa.Column('district_name', sa.String(), nullable=True),
    sa.Column('municipality_code', sa.String(), nullable=True),
    sa.Column('municipality_name', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_places_level'), 'places', ['level'], unique=False)
    op.create_index(op.f('ix_places_name'), 'places', ['name'], unique=False)
    op.create_index(op.f('ix_places_parent_place_code'), 'places', ['parent_place_code'], unique=False)
    op.create_index(op.f('ix_places_place_code'), 'places', ['place_code'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('operating_area', sa.String(), nullable=True),
    sa.Column('address_label', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_is_public', sa.Boolean(), nullable=False),
    sa.Column('service_radius_km', sa.Float(), nullable=True),
    sa.Column('service_area_notes', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('suburb', sa.String(), nullable=True),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('facebook_page_url', sa.String(), nullable=True),
    sa.Column('cover_photo_url', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('company_logo_url', sa.String(), nullable=True),
    sa.Column('supporting_image_urls', sa.JSON(), nullable=True),
    sa.Column('proof_of_work_items', sa.String(), nullable=True),
    sa.Column('provider_type', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('short_bio', sa.String(), nullable=True),
    sa.Column('business_category_key', sa.String(), nullable=True),
    sa.Column('business_line', sa.String(), nullable=True),
    sa.Column('services', sa.String(), nullable=True),
    sa.Column('contact_method', sa.String(), nullable=True),
    sa.Column('offer_types', sa.String(), nullable=True),
    sa.Column('pricing_style', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('languages', sa.String(), nullable=True),
    sa.Column('trust_posture', sa.String(), nullable=True),
    sa.Column('continuity_event_id', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('setup_fee_required', sa.Float(), nullable=True),
    sa.Column('setup_fee_status', sa.String(), nullable=True),
    sa.Column('setup_fee_proof_url', sa.String(), nullable=True),
    sa.Column('setup_fee_paid_at', sa.DateTime(), nullable=True),
    sa.Column('setup_fee_review_note', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('plan_code', sa.String(), nullable=False),
    sa.Column('subscription_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('referral_code', sa.String(), nullable=True),
    sa.Column('referred_by_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('referral_code'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_owner_id', sa.String(), nullable=False),
    sa.Column('customer_request_id', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('terms', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('quote_drafted', 'quote_reviewed', 'quote_sent', 'quote_accepted', 'quote_declined', 'quote_expired', 'quote_converted', 'issued', 'accepted', 'declined', name='quotestatus'), nullable=False),
    sa.Column('continuity_event_id', sa.UUID(), nullable=False),
    sa.Column('sent_continuity_event_id', sa.UUID(), nullable=True),
    sa.Column('accepted_continuity_event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vat', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('structured_terms', sa.JSON(), nullable=True),
    sa.Column('archetype_key', sa.String(), nullable=True),
    sa.Column('business_line', sa.String(), nullable=True),
    sa.Column('quote_template_version', sa.String(), nullable=False),
    sa.Column('share_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_business_owner_id'), 'quotes', ['business_owner_id'], unique=False)
    op.create_index(op.f('ix_quotes_share_token'), 'quotes', ['share_token'], unique=True)
    op.create_table('referrals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('referrer_profile_id', sa.String(), nullable=False),
    sa.Column('referred_profile_id', sa.String(), nullable=False),
    sa.Column('referral_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('reward_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('qualified_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_referred_profile_id'), 'referrals', ['referred_profile_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_profile_id'), 'referrals', ['referrer_profile_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('stock_added', 'stock_reserved', 'stock_allocated', 'stock_consumed', 'stock_adjusted', name='inventorymovementtype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('previous_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('next_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=False),
    sa.Column('continuity_event_id', sa.UUID(), nullable=False),
    sa.Column('balance_continuity_event_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_inventory_item_id'), 'inventory_movements', ['inventory_item_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_owner_id', sa.String(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('issued', 'paid', 'cancelled', name='invoicestatus'), nullable=False),
    sa.Column('continuity_event_id', sa.UUID(), nullable=False),
    sa.Column('paid_continuity_event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_business_owner_id'), 'invoices', ['business_owner_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by_profile_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('town_or_city', sa.String(), nullable=True),
    sa.Column('suburb_or_area', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('category_key', sa.String(), nullable=True),
    sa.Column('service_needed', sa.String(), nullable=True),
    sa.Column('budget_amount', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('image_url_1', sa.String(), nullable=True),
    sa.Column('image_url_2', sa.String(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_invoices_business_owner_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_inventory_movements_inventory_item_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_referrals_referrer_profile_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_profile_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_quotes_share_token'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_business_owner_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_places_place_code'), table_name='places')
    op.drop_index(op.f('ix_places_parent_place_code'), table_name='places')
    op.drop_index(op.f('ix_places_name'), table_name='places')
    op.drop_index(op.f('ix_places_level'), table_name='places')
    op.drop_table('places')
    op.drop_index(op.f('ix_leads_owner_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_inventory_items_business_owner_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_expenses_business_owner_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_continuity_events_lineage_sequence'), table_name='continuity_events')
    op.drop_table('continuity_events')
    # ### end Alembic commands ###
